/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.WindowConstants;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauri98
 */
public class Registrar_Usuarios extends javax.swing.JFrame {

    String user;

    public Registrar_Usuarios() {
        initComponents();
        user = Login.user;
        setTitle("Registrar nuevo usuario - Sesión de " + user);
        setSize(630, 350);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE); //Se evita que el programe finalice, cuando la ventana se cierra.

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png")); //No hace falta especificar el "src".
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_EtiquetaNameUser = new javax.swing.JLabel();
        label_EtiquetaEmail = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        label_EtiquetaCelular = new javax.swing.JLabel();
        txt_celular = new javax.swing.JTextField();
        label_EtiquetaPermisos = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        label_EtiquetaUsername = new javax.swing.JLabel();
        label_EtiquetaNombre = new javax.swing.JLabel();
        label_EtiquetaPassword = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        cmb_niveles = new javax.swing.JComboBox<>();
        btn_addUser = new javax.swing.JButton();
        label_footer = new javax.swing.JLabel();
        label_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_EtiquetaNameUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_EtiquetaNameUser.setForeground(new java.awt.Color(0, 0, 204));
        label_EtiquetaNameUser.setText("Registro de Usuarios");
        getContentPane().add(label_EtiquetaNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        label_EtiquetaEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_EtiquetaEmail.setForeground(new java.awt.Color(0, 0, 0));
        label_EtiquetaEmail.setText("Email:");
        getContentPane().add(label_EtiquetaEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(102, 102, 255));
        txt_nombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        txt_email.setBackground(new java.awt.Color(102, 102, 255));
        txt_email.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        label_EtiquetaCelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_EtiquetaCelular.setForeground(new java.awt.Color(0, 0, 0));
        label_EtiquetaCelular.setText("Celular:");
        getContentPane().add(label_EtiquetaCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txt_celular.setBackground(new java.awt.Color(102, 102, 255));
        txt_celular.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_celular.setForeground(new java.awt.Color(255, 255, 255));
        txt_celular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_celular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, -1));

        label_EtiquetaPermisos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_EtiquetaPermisos.setForeground(new java.awt.Color(0, 0, 0));
        label_EtiquetaPermisos.setText("Permisos de:");
        getContentPane().add(label_EtiquetaPermisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txt_username.setBackground(new java.awt.Color(102, 102, 255));
        txt_username.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, -1));

        label_EtiquetaUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_EtiquetaUsername.setForeground(new java.awt.Color(0, 0, 0));
        label_EtiquetaUsername.setText("Username:");
        getContentPane().add(label_EtiquetaUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        label_EtiquetaNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_EtiquetaNombre.setForeground(new java.awt.Color(0, 0, 0));
        label_EtiquetaNombre.setText("Nombre:");
        getContentPane().add(label_EtiquetaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        label_EtiquetaPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_EtiquetaPassword.setForeground(new java.awt.Color(0, 0, 0));
        label_EtiquetaPassword.setText("Password:");
        getContentPane().add(label_EtiquetaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        txt_password.setBackground(new java.awt.Color(102, 102, 255));
        txt_password.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setAutoscrolls(false);
        txt_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 210, -1));

        cmb_niveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Capturista", "Tecnico" }));
        getContentPane().add(cmb_niveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        btn_addUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addUserActionPerformed(evt);
            }
        });
        getContentPane().add(btn_addUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 120, 100));

        label_footer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_footer.setForeground(new java.awt.Color(0, 0, 255));
        label_footer.setText("Creado por N0x");
        getContentPane().add(label_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));
        getContentPane().add(label_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addUserActionPerformed
        int permisos_cmb, validacion = 0;
        String nombre, mail, celular, username, pass, permisos_string = "";

        mail = txt_email.getText().trim();
        nombre = txt_nombre.getText().trim();
        celular = txt_celular.getText().trim();
        username = txt_username.getText().trim();
        pass = txt_password.getText().trim();
        permisos_cmb = cmb_niveles.getSelectedIndex() + 1; //Al seleccionar un Item se le sumará un 1. Por ejemplo al seleccionar Admin será 1, al seleccionar Capturista será 2, y Técnico 3, se van sumando.

        if (mail.equals("")) {
            txt_email.setBackground(Color.RED);
            validacion++;
        }
        if (nombre.equals("")) {
            txt_nombre.setBackground(Color.RED);
            validacion++;
        }
        if (celular.equals("")) {
            txt_celular.setBackground(Color.RED);
            validacion++;
        }
        if (username.equals("")) {
            txt_username.setBackground(Color.RED);
            validacion++;
        }
        if (pass.equals("")) {
            txt_password.setBackground(Color.RED);
            validacion++;
        }

        if (permisos_cmb == 1) {
            permisos_string = "Administrador";
        } else if (permisos_cmb == 2) {
            permisos_string = "Capturista";
        } else if (permisos_cmb == 3) {
            permisos_string = "Tecnico";
        }

        //Se realiza la siguiente conexión para verificar y/o consultar a la DB que no haya otro usuario existente con ese nombre.
        try {
            Connection con = Conexion.conectar();
            PreparedStatement pst = con.prepareStatement("SELECT username FROM usuarios WHERE username = '" + username + "'");
            ResultSet rst = pst.executeQuery();

            if (rst.next()) {
                txt_username.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Nombre no disponible", "Usuario existente", JOptionPane.WARNING_MESSAGE);
                con.close();
            } else {
                if (validacion == 0) { //Si no hay ningún campo vacío.. se ejecuta la instrucción.
                    try {
                        Connection con2 = Conexion.conectar();
                        PreparedStatement pst2 = con.prepareStatement("INSERT INTO usuarios VALUES(?,?,?,?,?,?,?,?,?)");
                        pst2.setInt(1, 0); //Primer columna, ID.
                        pst2.setString(2, txt_nombre.getText().trim());
                        pst2.setString(3, txt_email.getText().trim());
                        pst2.setString(4, txt_celular.getText().trim());
                        pst2.setString(5, txt_username.getText().trim());
                        pst2.setString(6, txt_password.getText().trim());
                        pst2.setString(7, permisos_string); //Se guardará el rango según se haya seleccionado en el combobox.
                        pst2.setString(8, "Activo"); //Todo usuario al ingresar tendrá el estatuso de "Activo". Luego podrá cambiar.
                        pst2.setString(9, user);  //El usuario que esta en sesión será el que registre tal usuario y se guardará asi.

                        pst2.executeUpdate(); //Se actualizan los datos de la tabla.
                        con2.close(); //Se cierra la conexión.

                        Limpiar();

                        txt_nombre.setBackground(Color.GREEN);
                        txt_email.setBackground(Color.GREEN);
                        txt_celular.setBackground(Color.GREEN);
                        txt_username.setBackground(Color.GREEN);
                        txt_password.setBackground(Color.GREEN);

                        JOptionPane.showMessageDialog(null, "Registro exitoso");
                        this.dispose();
                        

                    } catch (SQLException e) {
                        System.err.println("Error en conexión a Base de Datos " + e);
                    }

                }

            }


        } catch (SQLException e) {
            System.err.println("Error en validar nombre de usuario " + e);
            JOptionPane.showMessageDialog(null, "Error al comparar usuario. Contacte con el Ingeniero xd", "Error 302", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_btn_addUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addUser;
    private javax.swing.JComboBox<String> cmb_niveles;
    private javax.swing.JLabel label_EtiquetaCelular;
    private javax.swing.JLabel label_EtiquetaEmail;
    private javax.swing.JLabel label_EtiquetaNameUser;
    private javax.swing.JLabel label_EtiquetaNombre;
    private javax.swing.JLabel label_EtiquetaPassword;
    private javax.swing.JLabel label_EtiquetaPermisos;
    private javax.swing.JLabel label_EtiquetaUsername;
    private javax.swing.JLabel label_Wallpaper;
    private javax.swing.JLabel label_footer;
    private javax.swing.JTextField txt_celular;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    public void Limpiar(){ //Método para limpiar los campos luego de registrar un usuario.
        txt_nombre.setText("");
        txt_email.setText("");
        txt_celular.setText("");
        txt_password.setText("");
        txt_username.setText("");
        cmb_niveles.setSelectedIndex(0);
        
    }


}
